### ISSUE TITLE
geen idea waar ik moet zijn

### ISSUE THREAD

**Issue by caspervanneck** [GameCraftPE/GMCPE-AntiCheat#1]
om the fixen

**Comment by Driesboy** [comment]
ik ook niet

**Comment by flaxues** [comment]
@Driesboy Ben je online?

**Comment by Driesboy** [comment]
ja

**Comment by flaxues** [comment]
@Driesboy Zou je je genisys phar voor 1.0.0 kunnen delen :)

**Comment by Driesboy** [comment]
ja over enkele uren

**Comment by flaxues** [comment]
@Driesboy Dankjewel

**Comment by Driesboy** [comment]
je moet wel credits geven he

**Comment by Driesboy** [comment]
dan krijg je hem nu

**Comment by flaxues** [comment]
@Driesboy Waar?

**Comment by Driesboy** [comment]
waar? op welke vraag

**Comment by Driesboy** [comment]
credits maakt niet uit
als er maar zijn

**Comment by Driesboy** [comment]
bv. in de lobby of zo

**Comment by flaxues** [comment]
Twitter ook goed dat ik je github link post?

**Comment by flaxues** [comment]
Oh en als je je bossbar eruit haalt heb je niet meer van die random droppende items of dat je elke keer slaat

**Comment by Driesboy** [comment]
bossbar thx voor de tip

**Comment by Driesboy** [comment]
nee mijn server ip

**Comment by flaxues** [comment]
@Driesboy Btw hoe kom jij eraan?

**Comment by Driesboy** [comment]
deployen

**Comment by Driesboy** [comment]
en debuggen

**Comment by Driesboy** [comment]
en dat heb ik gedaan voor de examens om tijdens de examens niets te moeten doen

**Comment by Driesboy** [comment]
https://github.com/Driesboy/Genisys-1.0.0

**Comment by Driesboy** [comment]
hier kan je het downloaden
